# Generated by Django 4.2.2 on 2023-07-01 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factory1', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ConfectioneryProduct',
            new_name='ConfectioneryFactoryproduct1',
        ),
    ]
